spring:
    application:
        name: anotacoes

    data:
        mongodb:
            uri: mongodb://localhost:27017/projeto-anotacoes

logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG